spring:
  cloud:
    stream:
      bindings:
        input:
          destination: money-transferred-exchange
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
server:
    port: 8081